`timescale 1ns/1ps

module bram_fifo_tb;
    // Generated by tools/gen_tb.py from rtl/common/bram_fifo.v

    localparam integer DATA_WIDTH = 8;
    localparam integer DEPTH = 4;

    reg clk = 0;
    reg rst_n = 0;
    reg wr_en = 0;
    reg [DATA_WIDTH-1:0] wr_data = 0;
    wire wr_valid_o;
    wire full;
    reg rd_en = 0;
    wire [DATA_WIDTH-1:0] rd_data;
    wire rd_valid_o;
    wire empty;

    always #5 clk = ~clk;

    bram_fifo #(
        .DATA_WIDTH(DATA_WIDTH),
        .DEPTH(DEPTH)
    ) dut (
        .clk(clk),
        .rst_n(rst_n),
        .wr_en(wr_en),
        .wr_data(wr_data),
        .wr_valid_o(wr_valid_o),
        .full(full),
        .rd_en(rd_en),
        .rd_data(rd_data),
        .rd_valid_o(rd_valid_o),
        .empty(empty)
    );

    initial begin
        $dumpfile("sim/bram_fifo.vcd");
        $dumpvars(0, bram_fifo_tb);

        #20;
        rst_n = 1'b1;

        #30 wr_en = 1'b1;
        #10 wr_en = 1'b0;
        #40 wr_en = 1'b1;
        #10 wr_en = 1'b0;
        #30 wr_data = 'h1;
        #50 wr_data = 'h0;
        #30 rd_en = 1'b1;
        #10 rd_en = 1'b0;
        #40 rd_en = 1'b1;
        #10 rd_en = 1'b0;

        #200;
        $finish;
    end
endmodule
