`timescale 1ns/1ps

module top_tb;
    // Generated by tools/gen_tb.py from rtl/top.v

    reg clk = 0;
    wire [5:0] led;

    always #5 clk = ~clk;

    top #(
        .CLK_HZ(10),
        .BLINK_HZ(5),
        .RESET_CYCLES(4)
    ) dut (
        .clk(clk),
        .led(led)
    );

    initial begin
        $dumpfile("sim/top.vcd");
        $dumpvars(0, top_tb);

        #300;
        $finish;
    end
endmodule
