`timescale 1ns/1ps

module uart_tx_tb;
    // Generated by tools/gen_tb.py from rtl/common/uart_tx.v

    localparam integer CLOCK_HZ = 100;
    localparam integer BAUD_RATE = 10;
    localparam integer BAUD_CNT_MAX = CLOCK_HZ / BAUD_RATE;

    reg clk = 0;
    reg rst_n = 0;
    reg [7:0] tx_data_i = 0;
    reg tx_valid_i = 0;
    wire tx_ready_o;
    wire tx_o;

    always #5 clk = ~clk;

    uart_tx #(
        .CLOCK_HZ(CLOCK_HZ),
        .BAUD_RATE(BAUD_RATE)
    ) dut (
        .clk(clk),
        .rst_n(rst_n),
        .tx_data_i(tx_data_i),
        .tx_valid_i(tx_valid_i),
        .tx_ready_o(tx_ready_o),
        .tx_o(tx_o)
    );

    task wait_bit;
        begin
            repeat (BAUD_CNT_MAX) @(posedge clk);
        end
    endtask

    task start_tx_byte;
        input [7:0] data;
        begin
            wait (tx_ready_o === 1'b1);
            @(negedge clk);
            tx_data_i = data;
            tx_valid_i = 1'b1;
            @(negedge clk);
            tx_valid_i = 1'b0;
        end
    endtask

    task check_tx_bit;
        input expected;
        begin
            if (tx_o !== expected) begin
                $display("FAIL: expected tx_o=%0b, got tx_o=%0b", expected, tx_o);
                $finish;
            end
        end
    endtask

    task expect_tx_byte;
        input [7:0] expected;
        integer i;
        begin
            wait (tx_o === 1'b0);
            repeat (BAUD_CNT_MAX / 2) @(posedge clk);
            check_tx_bit(1'b0);

            for (i = 0; i < 8; i = i + 1) begin
                wait_bit();
                check_tx_bit(expected[i]);
            end

            wait_bit();
            check_tx_bit(1'b1);

            wait (tx_ready_o === 1'b1);
            check_tx_bit(1'b1);
            $display("PASS: transmitted %02h", expected);
        end
    endtask

    initial begin
        $dumpfile("sim/uart_tx.vcd");
        $dumpvars(0, uart_tx_tb);

        repeat (4) @(posedge clk);
        rst_n = 1'b1;
        repeat (4) @(posedge clk);

        fork
            start_tx_byte(8'h55);
            expect_tx_byte(8'h55);
        join

        repeat (10) @(posedge clk);
        $display("uart_tx_tb PASS");
        $finish;
    end
endmodule
