`timescale 1ns/1ps

module axis_board_btn_tb;
    // Generated by tools/gen_tb.py from rtl/dvc/axis_board_btn.v

    localparam integer CLOCK_HZ = 100;
    localparam integer COUNT_MAX = 4;

    reg clk = 0;
    reg rst_n = 0;
    reg btn = 0;
    reg s_axis_tready_i = 0;
    wire s_axis_tvalid_o;
    wire selected_event_o;
    wire btn_level_o;

    always #5 clk = ~clk;

    axis_board_btn #(
        .CLOCK_HZ(CLOCK_HZ),
        .COUNT_MAX(COUNT_MAX)
    ) dut (
        .clk(clk),
        .rst_n(rst_n),
        .btn(btn),
        .s_axis_tready_i(s_axis_tready_i),
        .s_axis_tvalid_o(s_axis_tvalid_o),
        .selected_event_o(selected_event_o),
        .btn_level_o(btn_level_o)
    );

    initial begin
        $dumpfile("sim/axis_board_btn.vcd");
        $dumpvars(0, axis_board_btn_tb);

        #20;
        rst_n = 1'b1;

        #30 btn = 1'b1;
        #100 btn = 1'b0;
        #30 s_axis_tready_i = 1'b1;
        #50 s_axis_tready_i = 1'b0;

        #200;
        $finish;
    end
endmodule
