`timescale 1ns/1ps

module pwm_tb;
    // Generated by tools/gen_tb.py from rtl/common/pwm.v

    localparam integer CLOCK_HZ = 100;
    localparam integer PWM_HZ = 10;
    localparam integer PERIOD_COUNT = 16;
    localparam integer COUNT_WIDTH = 5;

    reg clk = 0;
    reg rst_n = 0;
    reg [COUNT_WIDTH-1:0] duty_i = 0;
    wire pwm_o;

    always #5 clk = ~clk;

    pwm #(
        .CLOCK_HZ(CLOCK_HZ),
        .PWM_HZ(PWM_HZ),
        .PERIOD_COUNT(PERIOD_COUNT),
        .COUNT_WIDTH(COUNT_WIDTH)
    ) dut (
        .clk(clk),
        .rst_n(rst_n),
        .duty_i(duty_i),
        .pwm_o(pwm_o)
    );

    initial begin
        $dumpfile("sim/pwm.vcd");
        $dumpvars(0, pwm_tb);

        #20;
        rst_n = 1'b1;

        #20 duty_i = 8;

        #200;
        $finish;
    end
endmodule
