`timescale 1ns/1ps

module top_tb;
    // Generated by tools/gen_tb.py from rtl/top.v

    reg clk = 0;
    reg btn = 0;
    wire [2:0] led;

    always #5 clk = ~clk;

    top dut (
        .clk(clk),
        .btn(btn),
        .led(led)
    );

    initial begin
        $dumpfile("sim/top.vcd");
        $dumpvars(0, top_tb);

        #20;

        #30 btn = 1'b1;
        #100 btn = 1'b0;

        #200;
        $finish;
    end
endmodule
