`timescale 1ns/1ps

module uart_rx_tb;
    // Generated by tools/gen_tb.py from rtl/common/uart_rx.v

    localparam integer CLOCK_HZ = 100;
    localparam integer BAUD_RATE = 10;
    localparam integer BAUD_CNT_MAX = CLOCK_HZ / BAUD_RATE;

    reg clk = 0;
    reg rst_n = 0;
    reg rx_i = 1'b1;
    wire [7:0] rx_data_o;
    wire rx_valid_o;
    wire frame_error_o;

    always #5 clk = ~clk;

    uart_rx #(
        .CLOCK_HZ(CLOCK_HZ),
        .BAUD_RATE(BAUD_RATE)
    ) dut (
        .clk(clk),
        .rst_n(rst_n),
        .rx_i(rx_i),
        .rx_data_o(rx_data_o),
        .rx_valid_o(rx_valid_o),
        .frame_error_o(frame_error_o)
    );

    task wait_bit;
        begin
            repeat (BAUD_CNT_MAX) @(posedge clk);
        end
    endtask

    task drive_bit;
        input bit_value;
        begin
            @(negedge clk);
            rx_i = bit_value;
            wait_bit();
        end
    endtask

    task send_uart_byte;
        input [7:0] data;
        integer i;
        begin
            drive_bit(1'b0);

            for (i = 0; i < 8; i = i + 1) begin
                drive_bit(data[i]);
            end

            drive_bit(1'b1);
            drive_bit(1'b1);
        end
    endtask

    task expect_byte;
        input [7:0] expected;
        integer timeout;
        begin
            timeout = BAUD_CNT_MAX * 12;

            while (rx_valid_o !== 1'b1 && timeout > 0) begin
                @(posedge clk);
                timeout = timeout - 1;
            end

            if (timeout == 0) begin
                $display("FAIL: timeout waiting for rx_valid_o");
                $finish;
            end

            if (rx_data_o !== expected) begin
                $display("FAIL: expected %02h, got %02h", expected, rx_data_o);
                $finish;
            end

            if (frame_error_o !== 1'b0) begin
                $display("FAIL: unexpected frame_error_o");
                $finish;
            end

            $display("PASS: received %02h", rx_data_o);
        end
    endtask

    initial begin
        $dumpfile("sim/uart_rx.vcd");
        $dumpvars(0, uart_rx_tb);

        repeat (4) @(posedge clk);
        rst_n = 1'b1;
        repeat (4) @(posedge clk);

        fork
            send_uart_byte(8'h55);
            expect_byte(8'h55);
        join

        repeat (10) @(posedge clk);
        $display("uart_rx_tb PASS");
        $finish;
    end
endmodule
